name: Main Workflow to Build and Push Biota DB Image

on:
  push:
    tags:
      - 'biota_db_*'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/build_image.yml
    with:
      registry: docker.io
      image_name: constellab/biota-db
      github_ref: ${{ github.ref }}
      tag_prefix: biota_db_
      dockerfile_path: ./database_image/Dockerfile
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}

  update_readme:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # step to set the docker image description from docker_hub_README.md
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: constellab/biota-db
          readme-filepath: ./database_image/README.md